graph TD
    subgraph "Fontes de Dados"
        API[API Pública ou CSV]
    end

    subgraph "Docker Compose"
        direction TB
        Airflow[Apache Airflow\n(Orquestrador)]
        
        subgraph "Data Lake (MinIO emulando S3)"
            Bronze[(Bronze\nRaw JSON/CSV)]
            Silver[(Silver\nParquet)]
            Gold[(Gold\nParquet Agregado)]
        end
        
        Postgres[(PostgreSQL\nCamada de Consumo)]
    end

    %% Fluxos de Orquestração
    Airflow -.->|Dispara task Ingestão| Task1
    Airflow -.->|Dispara task Limpeza| Task2
    Airflow -.->|Dispara task Agregação| Task3
    Airflow -.->|Dispara task Load| Task4

    %% Fluxo de Dados
    API -->|Python Requests| Task1(Script Bronze)
    Task1 --> Bronze
    
    Bronze -->|Pandas ou PySpark local| Task2(Script Silver)
    Task2 --> Silver
    
    Silver -->|Pandas ou PySpark local| Task3(Script Gold)
    Task3 --> Gold
    
    Gold -->|SQLAlchemy/psycopg2| Task4(Script DB Load)
    Task4 --> Postgres

    classDef aws fill:#FF9900,stroke:#232F3E,stroke-width:2px,color:black;
    classDef docker fill:#2496ED,stroke:#0db7ed,stroke-width:2px,color:white;
    classDef db fill:#336791,stroke:#232F3E,stroke-width:2px,color:white;
    
    class Airflow,Bronze,Silver,Gold docker;
    class Postgres db;